### PR TITLE
added "pls use pink" , made sleep time random, updated readme 

### PR DESCRIPTION
**Pull request by iceteacandy**
sleep time random to avoid bot detection

### CODE REVIEW

**Comment by kry0sc0pic** [comment]
@iceteacandy Thanks , just checked it out looks good. @Swayx113 merge?

**Review by swaylakh — CHANGES_REQUESTED** [review]
Just remove the code for pinks fgs

**Comment by kry0sc0pic** [comment]
I guess pink is fine as long as the user has permission to remove or add it @Swayx113 . @iceteacandy , could please make the following changes?
- Move the main.py out of the folder coz @Swayx113 dumb (jk).
- Make a config.py file where it has this 
```
enablePink=False
pinkTargetID = '270904126974590976'
```
- Add an if statement to read this value and decide to use pink or not , also use id from config file as well.

@Swayx113 can add config for others after merging your commit

Thanks Again @iceteacandy

**Comment by iceteacandy** [comment]
i had too many ideas in mind so i just worked on my own fork :)
thanks for the inspiration, feel free to contribute!

**Comment by kry0sc0pic** [comment]
@iceteacandy great work :) , @Swayx113 just test his changes and commit

**Pull request merged**
