### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by M-Python13**
_- Update memetypes list
- Add pls dig command(image below)
- Update read-me file accordingly_
pls dig

### CODE REVIEW

**Comment by M-Python13** [comment]
@Swayx113 Is this OK?

**Comment by M-Python13** [comment]
Oh, sorry for making a mess with my other two pull requests. My bad!

**Comment by M-Python13** [comment]
Oh and here evidence of the memetypes change.
[pls pm](https://user-images.githubusercontent.com/85016445/121561792-b92db500-ca10-11eb-912f-3682ceec273b.png)

**Comment by swaylakh** [comment]
ohk i was gonna add pls dig anyways but cool.

**Pull request merged**
