### PR TITLE
Update main.py

### PR DESCRIPTION
**Pull request by VeNoM-hubs**

### CODE REVIEW

**Review by kry0sc0pic — CHANGES_REQUESTED** [review]
Please separate the `pls hourly` and `pls daily` into separate threads since `time.sleep()` is a blocking function and would therefore reduce the efficiency.

**Comment by swaylakh** [comment]
Bad change

**Comment by VeNoM-hubs** [comment]
How do I separate?! Sent from Mail for Windows 10 From: Krishaay JoisSent: 14 October 2020 08:51To: Swayx113/dank-memer-auto-typerCc: VeNoM; AuthorSubject: Re: [Swayx113/dank-memer-auto-typer] Update main.py (#2) @krishaayjois21 requested changes on this pull request.Please separate the pls hourly and pls daily into separate threads since time.sleep() is a blocking function and would therefore reduce the efficiency.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by swaylakh** [comment]
What the

**Review by swaylakh — COMMENTED** [review]
No

**Pull request closed without merging**
